### ISSUE TITLE
error al querer crear la base de datos

### ISSUE THREAD

**Issue by francoav** [mangadventure/MangAdventure#14]
## Description
when wanting to create the database with the command "mangadventure migrate" it leaves error yaenv.core.EnvError: Missing environment variable: 'SITE_DOMAIN'

## Expected Behavior
create the database

## Actual Behavior
it not create the database

## Steps to Reproduce
![Captura 2PNG](https://user-images.githubusercontent.com/20564414/61283809-52031980-a783-11e9-835d-448028fc7b91.PNG)

## Your Environment

* MangAdventure version:v0.5.2
* Operating System and version:ubuntu 18.04
* Python version:Python 2.7.15+
* Web server and version:  Apache/2.4.29 (Ubuntu)
                                           Server built:   2019-04-03T13:22:37

**Comment by ObserverOfTime** [comment]
Did you [configure the settings](https://mangadventure.readthedocs.io/en/latest/install.html#configure-the-settings) as mentioned in the docs?

**Comment by francoav** [comment]
Yes 
https://prnt.sc/ofp0f2

https://prnt.sc/ofp0u9

**Comment by ObserverOfTime** [comment]
Turns out [yaenv](/ObserverOfTime/yaenv) can't find the `.env` file when ran from a different directory.
I'm resubmitting this issue there and will try to fix it ASAP.

**Comment by ObserverOfTime** [comment]
Actually, I thought we were using the absolute path for the `.env` file but we aren't. :thinking:
