### ISSUE TITLE
better theme

### ISSUE THREAD

**Issue by BrownIndianGuy** [mangadventure/MangAdventure#25]
## Description
NEED BETTER THEME SOOME THING LIKE  MY MANGA READER

## Context
current theme is worst feel like loading basic facebook :|

## Possible Implementation
make more look like  http://manga-panda.xyz/

## Your Environment
using the latest one

**Comment by ObserverOfTime** [comment]
That's Madara for WordPress. Feel free to use it instead.

Closed as duplicate of #22.

**Comment by BrownIndianGuy** [comment]
> That's Madara for WordPress. Feel free to use it instead.
> 
> Closed as duplicate of #22.

i know but its not free ;'(

can you make the interface more like a  website less like a forum . please?

**Comment by ObserverOfTime** [comment]
Yes, that's the point of the other issue.
