### ISSUE TITLE
Page-click navigation does not stop at the last page

### ISSUE THREAD

**Issue by Zi-SH** [mangadventure/MangAdventure#9]
## Description
Clicking a page allows you to progress to a page that doesn't exist.

## Expected Behavior
Either return to the Manga index or do not allow page progression on last page.

## Actual Behavior
Progresses to a page stating "SORRY. THIS PAGE DOESN'T EXIST."

## Possible Fix
Give it the same effect that the navigation arrows have on the final page.

## Steps to Reproduce
Browse to the last page of a manga. Click the manga page to progress one page.

## Your Environment
* Link to website: https://arc-relight.com/
* Operating System and version: Arch Linux 5.0.4-arch

**Comment by a-mere-peasant** [comment]
can i try to help with this ?

**Comment by ObserverOfTime** [comment]
Sure.
